version: "3.8"

services:
  app:
    restart: on-failure
    build: .
    environment:
      - PORT=4500
      - DB_URI=postgres://admin:admin@postgres:5432/db
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "4500:4500"
  
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
